# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projhuakuy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from openpyxl import load_workbook      
data = load_workbook('project.xlsx')    #import value from excel
dt = data.active


class Ui_HOUSELOAN(object):
    def setupUi(self, HOUSELOAN):
        HOUSELOAN.setObjectName("HOUSELOAN")
        HOUSELOAN.resize(597, 478)
        HOUSELOAN.setMinimumSize(QtCore.QSize(597, 478))
        HOUSELOAN.setMaximumSize(QtCore.QSize(597, 478))
        HOUSELOAN.setStyleSheet("\n"
"background-color: rgb(235, 240, 171);\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(HOUSELOAN)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 571, 431))
        self.stackedWidget.setObjectName("stackedWidget")

        #PAGE1
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.cus_name = QtWidgets.QTextEdit(self.page)
        self.cus_name.setGeometry(QtCore.QRect(210, 290, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.cus_name.setFont(font)
        self.cus_name.setStyleSheet("color: rgb(130,105,88)")
        self.cus_name.setObjectName("cus_name")
        self.next_btn = QtWidgets.QPushButton(self.page)
        self.next_btn.setGeometry(QtCore.QRect(280, 380, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.next_btn.setFont(font)
        self.next_btn.setStyleSheet("color: rgb(229,190,46);\n"
"background-color: rgb(130,105,88);")
        self.next_btn.setObjectName("next_btn")
        self.enter_name_label = QtWidgets.QLabel(self.page)
        self.enter_name_label.setGeometry(QtCore.QRect(240, 250, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.enter_name_label.setFont(font)
        self.enter_name_label.setObjectName("enter_name_label")
        self.titel_label = QtWidgets.QLabel(self.page)
        self.titel_label.setGeometry(QtCore.QRect(10, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.titel_label.setFont(font)
        self.titel_label.setStyleSheet("background-color:rgb(229,190,46)")
        self.titel_label.setScaledContents(False)
        self.titel_label.setObjectName("titel_label")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, -10, 571, 511))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setPixmap(QtGui.QPixmap("e8e9f92b1a74f417b8fbcb3d2d2874a8.jpg"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.cus_name.raise_()
        self.next_btn.raise_()
        self.enter_name_label.raise_()
        self.titel_label.raise_()
        self.stackedWidget.addWidget(self.page)

        #PAGE2
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.houseprice_txt = QtWidgets.QTextEdit(self.page_2)
        self.houseprice_txt.setGeometry(QtCore.QRect(340, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.houseprice_txt.setFont(font)
        self.houseprice_txt.setStyleSheet("color: rgb(130,105,88)")
        self.houseprice_txt.setObjectName("houseprice_txt")
        self.houseprice_label = QtWidgets.QLabel(self.page_2)
        self.houseprice_label.setGeometry(QtCore.QRect(340, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.houseprice_label.setFont(font)
        self.houseprice_label.setStyleSheet("color: rgb(130,105,88)")
        self.houseprice_label.setObjectName("houseprice_label")
        self.result_btn = QtWidgets.QPushButton(self.page_2)
        self.result_btn.setGeometry(QtCore.QRect(230, 360, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.result_btn.setFont(font)
        self.result_btn.setStyleSheet("color:rgb(203,119,59);\n"
"font: 75 10pt \"Comic Sans MS\";\n"
"background-color:rgb(229,190,46)")
        self.result_btn.setObjectName("result_btn")
        self.info_label = QtWidgets.QLabel(self.page_2)
        self.info_label.setGeometry(QtCore.QRect(200, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("color:rgb(203,119,59)")
        self.info_label.setObjectName("info_label")
        self.workBox = QtWidgets.QGroupBox(self.page_2)
        self.workBox.setGeometry(QtCore.QRect(50, 100, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.workBox.setFont(font)
        self.workBox.setStyleSheet("color:rgb(130,105,88);\n"
"border-color: rgb(229, 190, 46);")
        self.workBox.setObjectName("workBox")
        self.work_ren_rad = QtWidgets.QRadioButton(self.workBox)
        self.work_ren_rad.setGeometry(QtCore.QRect(130, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.work_ren_rad.setFont(font)
        self.work_ren_rad.setStyleSheet("color: rgb(130,105,88)")
        self.work_ren_rad.setObjectName("work_ren_rad")
        self.work_gen_rad = QtWidgets.QRadioButton(self.workBox)
        self.work_gen_rad.setGeometry(QtCore.QRect(30, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.work_gen_rad.setFont(font)
        self.work_gen_rad.setStyleSheet("color: rgb(130, 105, 88)")
        self.work_gen_rad.setObjectName("work_gen_rad")
        self.insuBox = QtWidgets.QGroupBox(self.page_2)
        self.insuBox.setGeometry(QtCore.QRect(50, 190, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.insuBox.setFont(font)
        self.insuBox.setStyleSheet("color:rgb(130,105,88);\n"
"border-color: rgb(229, 190, 46);")
        self.insuBox.setObjectName("insuBox")
        self.insu_no_rad = QtWidgets.QRadioButton(self.insuBox)
        self.insu_no_rad.setGeometry(QtCore.QRect(140, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.insu_no_rad.setFont(font)
        self.insu_no_rad.setStyleSheet("color: rgb(130,105,88)\n"
"")
        self.insu_no_rad.setObjectName("insu_no_rad")
        self.insu_yes_rad = QtWidgets.QRadioButton(self.insuBox)
        self.insu_yes_rad.setGeometry(QtCore.QRect(40, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.insu_yes_rad.setFont(font)
        self.insu_yes_rad.setStyleSheet("color: rgb(130,105,88)")
        self.insu_yes_rad.setObjectName("insu_yes_rad")
        self.calculate_btn = QtWidgets.QPushButton(self.page_2)
        self.calculate_btn.setGeometry(QtCore.QRect(230, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.calculate_btn.setFont(font)
        self.calculate_btn.setStyleSheet("color:rgb(203,119,59);\n"
"font: 75 10pt \"Comic Sans MS\";\n"
"background-color:rgb(229,190,46)")
        self.calculate_btn.setObjectName("calculate_btn")
        self.time_comboBox = QtWidgets.QComboBox(self.page_2)
        self.time_comboBox.setGeometry(QtCore.QRect(340, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.time_comboBox.setFont(font)
        self.time_comboBox.setStyleSheet("color:rgb(130,105,88)")
        self.time_comboBox.setObjectName("time_comboBox")
        self.time_comboBox.addItem("10")
        self.time_comboBox.addItem("15")
        self.time_comboBox.addItem("20")
        self.time_comboBox.addItem("25")
        self.time_comboBox.addItem("30")
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setGeometry(QtCore.QRect(340, 190, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:rgb(130,105,88)")
        self.label_30.setObjectName("label_30")
        self.insuBox.raise_()
        self.workBox.raise_()
        self.houseprice_txt.raise_()
        self.houseprice_label.raise_()
        self.result_btn.raise_()
        self.info_label.raise_()
        self.calculate_btn.raise_()
        self.time_comboBox.raise_()
        self.label_30.raise_()
        self.stackedWidget.addWidget(self.page_2)

        #PAGE3
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.overall_label = QtWidgets.QLabel(self.page_3)
        self.overall_label.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.overall_label.setFont(font)
        self.overall_label.setObjectName("overall_label")
        self.BKB = QtWidgets.QLabel(self.page_3)
        self.BKB.setGeometry(QtCore.QRect(70, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.BKB.setFont(font)
        self.BKB.setObjectName("BKB")
        self.golastpg_btn = QtWidgets.QPushButton(self.page_3)
        self.golastpg_btn.setGeometry(QtCore.QRect(480, 390, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.golastpg_btn.setFont(font)
        self.golastpg_btn.setStyleSheet("color:rgb(229,190,46);\n"
"background-color: rgb(203,119,59)")
        self.golastpg_btn.setObjectName("golastpg_btn")
        self.BOA = QtWidgets.QLabel(self.page_3)
        self.BOA.setGeometry(QtCore.QRect(70, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.BOA.setFont(font)
        self.BOA.setObjectName("BOA")
        self.CIMB = QtWidgets.QLabel(self.page_3)
        self.CIMB.setGeometry(QtCore.QRect(70, 130, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.CIMB.setFont(font)
        self.CIMB.setStyleSheet("color:rgb(203,119,59)")
        self.CIMB.setObjectName("CIMB")
        self.GSB = QtWidgets.QLabel(self.page_3)
        self.GSB.setGeometry(QtCore.QRect(70, 170, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.GSB.setFont(font)
        self.GSB.setObjectName("GSB")
        self.KBANK = QtWidgets.QLabel(self.page_3)
        self.KBANK.setGeometry(QtCore.QRect(70, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.KBANK.setFont(font)
        self.KBANK.setObjectName("KBANK")
        self.KTB = QtWidgets.QLabel(self.page_3)
        self.KTB.setGeometry(QtCore.QRect(70, 250, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.KTB.setFont(font)
        self.KTB.setObjectName("KTB")
        self.LHB = QtWidgets.QLabel(self.page_3)
        self.LHB.setGeometry(QtCore.QRect(70, 290, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.LHB.setFont(font)
        self.LHB.setObjectName("LHB")
        self.SCB = QtWidgets.QLabel(self.page_3)
        self.SCB.setGeometry(QtCore.QRect(70, 330, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.SCB.setFont(font)
        self.SCB.setObjectName("SCB")
        self.TMB = QtWidgets.QLabel(self.page_3)
        self.TMB.setGeometry(QtCore.QRect(70, 370, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.TMB.setFont(font)
        self.TMB.setObjectName("TMB")
        self.UOB = QtWidgets.QLabel(self.page_3)
        self.UOB.setGeometry(QtCore.QRect(70, 410, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.UOB.setFont(font)
        self.UOB.setObjectName("UOB")
        self.BKB_pay = QtWidgets.QLabel(self.page_3)
        self.BKB_pay.setGeometry(QtCore.QRect(170, 50, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.BKB_pay.setFont(font)
        self.BKB_pay.setStyleSheet("color:rgb(130,105,88)")
        #self.BKB_pay.setText("")
        self.BKB_pay.setObjectName("BKB_pay")
        self.BOA_pay = QtWidgets.QLabel(self.page_3)
        self.BOA_pay.setGeometry(QtCore.QRect(190, 90, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.BOA_pay.setFont(font)
        self.BOA_pay.setStyleSheet("color:rgb(130,105,88)")
        self.BOA_pay.setText("")
        self.BOA_pay.setObjectName("BOA_pay")
        self.CIMB_pay = QtWidgets.QLabel(self.page_3)
        self.CIMB_pay.setGeometry(QtCore.QRect(160, 130, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.CIMB_pay.setFont(font)
        self.CIMB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.CIMB_pay.setText("")
        self.CIMB_pay.setObjectName("CIMB_pay")
        self.GSB_pay = QtWidgets.QLabel(self.page_3)
        self.GSB_pay.setGeometry(QtCore.QRect(230, 170, 291, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.GSB_pay.setFont(font)
        self.GSB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.GSB_pay.setText("")
        self.GSB_pay.setObjectName("GSB_pay")
        self.KBANK_pay = QtWidgets.QLabel(self.page_3)
        self.KBANK_pay.setGeometry(QtCore.QRect(160, 210, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.KBANK_pay.setFont(font)
        self.KBANK_pay.setStyleSheet("color:rgb(130,105,88)")
        self.KBANK_pay.setText("")
        self.KBANK_pay.setObjectName("KBANK_pay")
        self.KTB_pay = QtWidgets.QLabel(self.page_3)
        self.KTB_pay.setGeometry(QtCore.QRect(180, 250, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.KTB_pay.setFont(font)
        self.KTB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.KTB_pay.setText("")
        self.KTB_pay.setObjectName("KTB_pay")
        self.LHB_pay = QtWidgets.QLabel(self.page_3)
        self.LHB_pay.setGeometry(QtCore.QRect(140, 290, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.LHB_pay.setFont(font)
        self.LHB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.LHB_pay.setText("")
        self.LHB_pay.setObjectName("LHB_pay")
        self.SCB_pay = QtWidgets.QLabel(self.page_3)
        self.SCB_pay.setGeometry(QtCore.QRect(220, 330, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.SCB_pay.setFont(font)
        self.SCB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.SCB_pay.setText("")
        self.SCB_pay.setObjectName("SCB_pay")
        self.TMB_pay = QtWidgets.QLabel(self.page_3)
        self.TMB_pay.setGeometry(QtCore.QRect(150, 370, 321, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.TMB_pay.setFont(font)
        self.TMB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.TMB_pay.setText("")
        self.TMB_pay.setObjectName("TMB_pay")
        self.UOB_pay = QtWidgets.QLabel(self.page_3)
        self.UOB_pay.setGeometry(QtCore.QRect(210, 410, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.UOB_pay.setFont(font)
        self.UOB_pay.setStyleSheet("color:rgb(130,105,88)")
        self.UOB_pay.setText("")
        self.UOB_pay.setObjectName("UOB_pay")
        self.stackedWidget.addWidget(self.page_3)

        #PAGE4
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(229,190,46);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.lowest_bank_1 = QtWidgets.QLabel(self.page_4)
        self.lowest_bank_1.setGeometry(QtCore.QRect(110, 140, 230, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lowest_bank_1.setFont(font)
        self.lowest_bank_1.setStyleSheet("color:rgb(130,105,88)")
        self.lowest_bank_1.setText("")
        self.lowest_bank_1.setObjectName("lowest_bank_1")
        self.label_26 = QtWidgets.QLabel(self.page_4)
        self.label_26.setGeometry(QtCore.QRect(450, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:rgb(130,105,88)")
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.page_4)
        self.label_28.setGeometry(QtCore.QRect(90, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:rgb(203,119,59)")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.page_4)
        self.label_29.setGeometry(QtCore.QRect(180, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:rgb(203,119,59)")
        self.label_29.setObjectName("label_29")
        self.home_btn = QtWidgets.QPushButton(self.page_4)
        self.home_btn.setGeometry(QtCore.QRect(170, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.home_btn.setFont(font)
        self.home_btn.setStyleSheet("color:rgb(130,105,88);\n"
"background-color: rgb(229,190,46)")
        self.home_btn.setObjectName("home_btn")
        self.exit_btn = QtWidgets.QPushButton(self.page_4)
        self.exit_btn.setGeometry(QtCore.QRect(310, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("color:rgb(229,190,46);\n"
"background-color: rgb(203,119,59)")
        self.exit_btn.setObjectName("exit_btn")
        self.lowest_pay_1 = QtWidgets.QLabel(self.page_4)
        self.lowest_pay_1.setGeometry(QtCore.QRect(370, 150, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lowest_pay_1.setFont(font)
        self.lowest_pay_1.setStyleSheet("color:rgb(130,105,88);\n"
"")
        self.lowest_pay_1.setText("")
        self.lowest_pay_1.setObjectName("lowest_pay_1")
        self.lowest_bank_2 = QtWidgets.QLabel(self.page_4)
        self.lowest_bank_2.setGeometry(QtCore.QRect(110, 210, 230, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lowest_bank_2.setFont(font)
        self.lowest_bank_2.setStyleSheet("color:rgb(130,105,88)")
        self.lowest_bank_2.setText("")
        self.lowest_bank_2.setObjectName("lowest_bank_2")
        self.lowest_bank_3 = QtWidgets.QLabel(self.page_4)
        self.lowest_bank_3.setGeometry(QtCore.QRect(110, 280, 230, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lowest_bank_3.setFont(font)
        self.lowest_bank_3.setStyleSheet("color:rgb(130,105,88)")
        self.lowest_bank_3.setText("")
        self.lowest_bank_3.setObjectName("lowest_bank_3")
        self.lowest_pay_2 = QtWidgets.QLabel(self.page_4)
        self.lowest_pay_2.setGeometry(QtCore.QRect(370, 220, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lowest_pay_2.setFont(font)
        self.lowest_pay_2.setStyleSheet("color:rgb(130,105,88);\n"
"")
        self.lowest_pay_2.setText("")
        self.lowest_pay_2.setObjectName("lowest_pay_2")
        self.lowest_pay_3 = QtWidgets.QLabel(self.page_4)
        self.lowest_pay_3.setGeometry(QtCore.QRect(370, 290, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.lowest_pay_3.setFont(font)
        self.lowest_pay_3.setStyleSheet("color:rgb(130,105,88);\n"
"")
        self.lowest_pay_3.setText("")
        self.lowest_pay_3.setObjectName("lowest_pay_3")
        self.label_47 = QtWidgets.QLabel(self.page_4)
        self.label_47.setGeometry(QtCore.QRect(450, 220, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color:rgb(130,105,88)")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_4)
        self.label_48.setGeometry(QtCore.QRect(450, 290, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color:rgb(130,105,88)")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_4)
        self.label_49.setGeometry(QtCore.QRect(40, 120, 51, 61))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("1-removebg-preview.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.name_label = QtWidgets.QLabel(self.page_4)
        self.name_label.setGeometry(QtCore.QRect(310, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color:rgb(229,190,46)")
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.label_50 = QtWidgets.QLabel(self.page_4)
        self.label_50.setGeometry(QtCore.QRect(40, 190, 51, 61))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("2-removebg-preview.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.page_4)
        self.label_51.setGeometry(QtCore.QRect(40, 260, 51, 61))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("3-removebg-preview.png"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.stackedWidget.addWidget(self.page_4)
        HOUSELOAN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HOUSELOAN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 21))
        self.menubar.setObjectName("menubar")
        HOUSELOAN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HOUSELOAN)
        self.statusbar.setObjectName("statusbar")
        HOUSELOAN.setStatusBar(self.statusbar)

        self.retranslateUi(HOUSELOAN)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HOUSELOAN)

        
## MY CODE ##


    #Group Box Radio Button Code
        self.workBox.setFlat(True)
        self.hbox1 = QtWidgets.QHBoxLayout()
        self.hbox1.addWidget(self.work_gen_rad)
        self.hbox1.addWidget(self.work_ren_rad)
        self.workBox.setLayout(self.hbox1)
        
        self.insuBox.setFlat(True)
        self.hbox2 = QtWidgets.QHBoxLayout()
        self.hbox2.addWidget(self.insu_yes_rad)
        self.hbox2.addWidget(self.insu_no_rad)
        self.insuBox.setLayout(self.hbox2)
        
    #Link Radio Button to Python Code
        self.work_gen_rad.clicked.connect(self.work)
        self.work_ren_rad.clicked.connect(self.work)

        self.insu_yes_rad.clicked.connect(self.insu)
        self.insu_no_rad.clicked.connect(self.insu)
        
    #Clicked Button Code 
        self.next_btn.clicked.connect(self.gopage2)
        self.calculate_btn.clicked.connect(self.calculate)
        self.result_btn.clicked.connect(self.gopage3)
        self.golastpg_btn.clicked.connect(self.golastpage)
        self.home_btn.clicked.connect(self.gohome)
        self.exit_btn.clicked.connect(self.exitapp)

    
    def gopage2(self): 
        self.stackedWidget.setCurrentIndex(1)

    def gopage3(self):
        self.stackedWidget.setCurrentIndex(2)

    def golastpage(self):
        self.stackedWidget.setCurrentIndex(3)

    def gohome(self):
        self.stackedWidget.setCurrentIndex(0)

    def exitapp(self):
        os.system(cmd)
        self.QtCore.QCoreApplication.instance().quit()


    def work(self):
        if self.work_gen_rad.isChecked():       
            w = 1
        elif self.work_ren_rad.isChecked():
            w = 2

    def insu(self):
        if self.insu_yes_rad.isChecked():
            i = 3
        elif self.insu_no_rad.isChecked():
            i = 4        
        

    #Calculate House Loan
    def calculate(self):
        houseprice = self.houseprice_txt.toPlainText()  #Get house price
        houseprice = int(houseprice)
        
        name = self.cus_name.toPlainText()      #Get user's name
        self.name_label.setText(str(name)+"!")  #Print Out user's name in page 4
        
        time = self.time_comboBox.currentText() #Get value from Combo Box
        time = int(time)*12

        if self.work_gen_rad.isChecked():       #Get value from Radio Button
            w = 1
        elif self.work_ren_rad.isChecked():
            w = 2

        if self.insu_yes_rad.isChecked():
            i = 3
        elif self.insu_no_rad.isChecked():
            i = 4

        #Create user's infomation list
        self.lst = []
        self.lst.insert(0,w)
        self.lst.insert(1,i)
        self.lst.insert(2,houseprice)
        self.lst.insert(3,time)
        
        #Get value from excel
        if self.lst[0]==1:
            if self.lst[1]==3:
                if 500000 <= self.lst[2] and self.lst[2] <= 999999:
                    bkb_rate = dt.cell(row=4,column=2)
                    boa_rate = dt.cell(row=5,column=2)
                    cimb_rate = dt.cell(row=6,column=2)
                    gsb_rate = dt.cell(row=7,column=2)
                    kbank_rate = dt.cell(row=8,column=2)
                    ktb_rate = dt.cell(row=9,column=2)
                    lhb_rate = dt.cell(row=10,column=2)
                    scb_rate = dt.cell(row=11,column=2)
                    tmb_rate = dt.cell(row=12,column=2)
                    uob_rate = dt.cell(row=13,column=2)                   
                elif 1000000 <= self.lst[2] and self.lst[2] <= 2999999:
                    bkb_rate = dt.cell(row=4,column=3)
                    boa_rate = dt.cell(row=5,column=3)
                    cimb_rate = dt.cell(row=6,column=3)
                    gsb_rate = dt.cell(row=7,column=3)
                    kbank_rate = dt.cell(row=8,column=3)
                    ktb_rate = dt.cell(row=9,column=3)
                    lhb_rate = dt.cell(row=10,column=3)
                    scb_rate = dt.cell(row=11,column=3)
                    tmb_rate = dt.cell(row=12,column=3)
                    uob_rate = dt.cell(row=13,column=3)
                elif 3000000<= self.lst[2] and self.lst[2]<= 4999999:
                    bkb_rate = dt.cell(row=4,column=4)
                    boa_rate = dt.cell(row=5,column=4)
                    cimb_rate = dt.cell(row=6,column=4)
                    gsb_rate = dt.cell(row=7,column=4)
                    kbank_rate = dt.cell(row=8,column=4)
                    ktb_rate = dt.cell(row=9,column=4)
                    lhb_rate = dt.cell(row=10,column=4)
                    scb_rate = dt.cell(row=11,column=4)
                    tmb_rate = dt.cell(row=12,column=4)
                    uob_rate = dt.cell(row=13,column=4)
                elif self.lst[2] >= 5000000:
                    bkb_rate = dt.cell(row=4,column=5)
                    boa_rate = dt.cell(row=5,column=5)
                    cimb_rate = dt.cell(row=6,column=5)
                    gsb_rate = dt.cell(row=7,column=5)
                    kbank_rate = dt.cell(row=8,column=5)
                    ktb_rate = dt.cell(row=9,column=5)
                    lhb_rate = dt.cell(row=10,column=5)
                    scb_rate = dt.cell(row=11,column=5)
                    tmb_rate = dt.cell(row=12,column=5)
                    uob_rate = dt.cell(row=13,column=5)
            elif self.lst[1]==4:
                if 500000 <= self.lst[2] and self.lst[2] <= 999999:
                    bkb_rate = dt.cell(row=4,column=6)
                    boa_rate = dt.cell(row=5,column=6)
                    cimb_rate = dt.cell(row=6,column=6)
                    gsb_rate = dt.cell(row=7,column=6)
                    kbank_rate = dt.cell(row=8,column=6)
                    ktb_rate = dt.cell(row=9,column=6)
                    lhb_rate = dt.cell(row=10,column=6)
                    scb_rate = dt.cell(row=11,column=6)
                    tmb_rate = dt.cell(row=12,column=6)
                    uob_rate = dt.cell(row=13,column=6)                   
                elif 1000000 <= self.lst[2] and self.lst[2] <= 2999999:
                    bkb_rate = dt.cell(row=4,column=7)
                    boa_rate = dt.cell(row=5,column=7)
                    cimb_rate = dt.cell(row=6,column=7)
                    gsb_rate = dt.cell(row=7,column=7)
                    kbank_rate = dt.cell(row=8,column=7)
                    ktb_rate = dt.cell(row=9,column=7)
                    lhb_rate = dt.cell(row=10,column=7)
                    scb_rate = dt.cell(row=11,column=7)
                    tmb_rate = dt.cell(row=12,column=7)
                    uob_rate = dt.cell(row=13,column=7)
                elif 3000000<= self.lst[2] and self.lst[2]<= 4999999:
                    bkb_rate = dt.cell(row=4,column=8)
                    boa_rate = dt.cell(row=5,column=8)
                    cimb_rate = dt.cell(row=6,column=8)
                    gsb_rate = dt.cell(row=7,column=8)
                    kbank_rate = dt.cell(row=8,column=8)
                    ktb_rate = dt.cell(row=9,column=8)
                    lhb_rate = dt.cell(row=10,column=8)
                    scb_rate = dt.cell(row=11,column=8)
                    tmb_rate = dt.cell(row=12,column=8)
                    uob_rate = dt.cell(row=13,column=8)
                elif self.lst[2] >= 5000000:
                    bkb_rate = dt.cell(row=4,column=9)
                    boa_rate = dt.cell(row=5,column=9)
                    cimb_rate = dt.cell(row=6,column=9)
                    gsb_rate = dt.cell(row=7,column=9)
                    kbank_rate = dt.cell(row=8,column=9)
                    ktb_rate = dt.cell(row=9,column=9)
                    lhb_rate = dt.cell(row=10,column=9)
                    scb_rate = dt.cell(row=11,column=9)
                    tmb_rate = dt.cell(row=12,column=9)
                    uob_rate = dt.cell(row=13,column=9)
        elif self.lst[0]==2:
            if self.lst[1]==3:
                if 500000 <= self.lst[2] and self.lst[2] <= 999999:
                    bkb_rate = dt.cell(row=4,column=10)
                    boa_rate = dt.cell(row=5,column=10)
                    cimb_rate = dt.cell(row=6,column=10)
                    gsb_rate = dt.cell(row=7,column=10)
                    kbank_rate = dt.cell(row=8,column=10)
                    ktb_rate = dt.cell(row=9,column=10)
                    lhb_rate = dt.cell(row=10,column=10)
                    scb_rate = dt.cell(row=11,column=10)
                    tmb_rate = dt.cell(row=12,column=10)
                    uob_rate = dt.cell(row=13,column=10)                   
                elif 1000000 <= self.lst[2] and self.lst[2] <= 2999999:
                    bkb_rate = dt.cell(row=4,column=11)
                    boa_rate = dt.cell(row=5,column=11)
                    cimb_rate = dt.cell(row=6,column=11)
                    gsb_rate = dt.cell(row=7,column=11)
                    kbank_rate = dt.cell(row=8,column=11)
                    ktb_rate = dt.cell(row=9,column=11)
                    lhb_rate = dt.cell(row=10,column=11)
                    scb_rate = dt.cell(row=11,column=11)
                    tmb_rate = dt.cell(row=12,column=11)
                    uob_rate = dt.cell(row=13,column=11)
                elif 3000000<= self.lst[2] and self.lst[2]<= 4999999:
                    bkb_rate = dt.cell(row=4,column=12)
                    boa_rate = dt.cell(row=5,column=12)
                    cimb_rate = dt.cell(row=6,column=12)
                    gsb_rate = dt.cell(row=7,column=12)
                    kbank_rate = dt.cell(row=8,column=12)
                    ktb_rate = dt.cell(row=9,column=12)
                    lhb_rate = dt.cell(row=10,column=12)
                    scb_rate = dt.cell(row=11,column=12)
                    tmb_rate = dt.cell(row=12,column=12)
                    uob_rate = dt.cell(row=13,column=12)
                elif self.lst[2] >= 5000000:
                    bkb_rate = dt.cell(row=4,column=13)
                    boa_rate = dt.cell(row=5,column=13)
                    cimb_rate = dt.cell(row=6,column=13)
                    gsb_rate = dt.cell(row=7,column=13)
                    kbank_rate = dt.cell(row=8,column=13)
                    ktb_rate = dt.cell(row=9,column=13)
                    lhb_rate = dt.cell(row=10,column=13)
                    scb_rate = dt.cell(row=11,column=13)
                    tmb_rate = dt.cell(row=12,column=13)
                    uob_rate = dt.cell(row=13,column=13)
            elif self.lst[1]==4:
                if 500000 <= self.lst[2] and self.lst[2] <= 999999:
                    bkb_rate = dt.cell(row=4,column=14)
                    boa_rate = dt.cell(row=5,column=14)
                    cimb_rate = dt.cell(row=6,column=14)
                    gsb_rate = dt.cell(row=7,column=14)
                    kbank_rate = dt.cell(row=8,column=14)
                    ktb_rate = dt.cell(row=9,column=14)
                    lhb_rate = dt.cell(row=10,column=14)
                    scb_rate = dt.cell(row=11,column=14)
                    tmb_rate = dt.cell(row=12,column=14)
                    uob_rate = dt.cell(row=13,column=14)                   
                elif 1000000 <= self.lst[2] and self.lst[2] <= 2999999:
                    bkb_rate = dt.cell(row=4,column=15)
                    boa_rate = dt.cell(row=5,column=15)
                    cimb_rate = dt.cell(row=6,column=15)
                    gsb_rate = dt.cell(row=7,column=15)
                    kbank_rate = dt.cell(row=8,column=15)
                    ktb_rate = dt.cell(row=9,column=15)
                    lhb_rate = dt.cell(row=10,column=15)
                    scb_rate = dt.cell(row=11,column=15)
                    tmb_rate = dt.cell(row=12,column=15)
                    uob_rate = dt.cell(row=13,column=15)
                elif 3000000<= self.lst[2] and self.lst[2]<= 4999999:
                    bkb_rate = dt.cell(row=4,column=16)
                    boa_rate = dt.cell(row=5,column=16)
                    cimb_rate = dt.cell(row=6,column=16)
                    gsb_rate = dt.cell(row=7,column=16)
                    kbank_rate = dt.cell(row=8,column=16)
                    ktb_rate = dt.cell(row=9,column=16)
                    lhb_rate = dt.cell(row=10,column=16)
                    scb_rate = dt.cell(row=11,column=16)
                    tmb_rate = dt.cell(row=12,column=16)
                    uob_rate = dt.cell(row=13,column=16)
                elif self.lst[2] >= 5000000:
                    bkb_rate = dt.cell(row=4,column=17)
                    boa_rate = dt.cell(row=5,column=17)
                    cimb_rate = dt.cell(row=6,column=17)
                    gsb_rate = dt.cell(row=7,column=17)
                    kbank_rate = dt.cell(row=8,column=17)
                    ktb_rate = dt.cell(row=9,column=17)
                    lhb_rate = dt.cell(row=10,column=17)
                    scb_rate = dt.cell(row=11,column=17)
                    tmb_rate = dt.cell(row=12,column=17)
                    uob_rate = dt.cell(row=13,column=17)
        
                    
        #Append Value in value dictionary
        self.rate_value = {}
        self.rate_value["BKB"] = bkb_rate.value
        self.rate_value["BOA"] = boa_rate.value
        self.rate_value["CIMB"] = cimb_rate.value
        self.rate_value["GSB"] = gsb_rate.value
        self.rate_value["KBANK"] = kbank_rate.value
        self.rate_value["KTB"] = ktb_rate.value
        self.rate_value["LHB"] = lhb_rate.value
        self.rate_value["SCB"] = scb_rate.value
        self.rate_value["TMB"] = tmb_rate.value
        self.rate_value["UOB"] = uob_rate.value

          
        #Calculate each Bank
        self.rate = {}
        self.pay = {}
        for each_rate,i in self.rate_value.items():
            r = (i/100)/12
            self.rate[each_rate] = r            
        for each,j in self.rate.items():
            if self.rate.get(each) == 0:
                self.pay[each] = 0
            else:
                each_pay = self.lst[2]*(self.rate.get(each)/(1-((1+self.rate.get(each))**(time*(-1)))))
                self.pay[each] = round(each_pay,2)
        
        
        #Show Result in Page 3
        self.BKB_pay.setText("pay average "+str(self.pay["BKB"])+" THB per month")
        self.BOA_pay.setText("pay average "+str(self.pay["BOA"])+" THB per month")
        self.CIMB_pay.setText("pay average "+str(self.pay["CIMB"])+" THB per month")
        self.GSB_pay.setText("pay average "+str(self.pay["GSB"])+" THB per month")
        self.KBANK_pay.setText("pay average "+str(self.pay["KBANK"])+" THB per month")
        self.KTB_pay.setText("pay average "+str(self.pay["KTB"])+" THB per month")
        self.LHB_pay.setText("pay average "+str(self.pay["LHB"])+" THB per month")
        self.SCB_pay.setText("pay average "+str(self.pay["SCB"])+" THB per month")
        self.TMB_pay.setText("pay average "+str(self.pay["TMB"])+" THB per month")
        self.UOB_pay.setText("pay average "+str(self.pay["UOB"])+" THB per month")


        #Find lowest
        low1 = self.pay["BKB"]
        for bank,k in self.pay.items():
            if k <= low1:
                low1 = k
                
        low2 = int(low1) + 1
        for bank,k in self.pay.items():
            if low1 < k:
                low2 = k
                
        low3 = int(low2) + 1
        for bank,k in self.pay.items():
            if low2 < k:
                low3 = k
        
        if low1 == self.pay["BKB"]:
            self.lowest_bank_1.setText("BANGKOK BANK")
        elif low1 == self.pay["BOA"]:
            self.lowest_bank_1.setText("BANG OF AYUDHYA")
        elif low1 == self.pay["CIMB"]:
            self.lowest_bank_1.setText("CIMB BANK")
        elif low1 == self.pay["GSB"]:
            self.lowest_bank_1.setText("GOVERNMENT SAVING BANK")
        elif low1 == self.pay["KBANK"]:
            self.lowest_bank_1.setText("KASIKORN BANK")
        elif low1 == self.pay["KTB"]:
            self.lowest_bank_1.setText("KRUNG THAI BANK")
        elif low1 == self.pay["LHB"]:
            self.lowest_bank_1.setText("LH BANK")
        elif low1 == self.pay["SCB"]:
            self.lowest_bank_1.setText("SIAM COMMERCIAL BANK")
        elif low1 == self.pay["TMB"]:
            self.lowest_bank_1.setText("TMB BANK")
        elif low1 == self.pay["UOB"]:
            self.lowest_bank_1.setText("KASIKORN BANK")
        self.lowest_pay_1.setText(str(low1))

        if low2 == self.pay["BKB"]:
            self.lowest_bank_2.setText("BANGKOK BANK")
        elif low2 == self.pay["BOA"]:
            self.lowest_bank_2.setText("BANG OF AYUDHYA")
        elif low2 == self.pay["CIMB"]:
            self.lowest_bank_2.setText("CIMB BANK")
        elif low2 == self.pay["GSB"]:
            self.lowest_bank_2.setText("GOVERNMENT SAVING BANK")
        elif low2 == self.pay["KBANK"]:
            self.lowest_bank_2.setText("KASIKORN BANK")
        elif low2 == self.pay["KTB"]:
            self.lowest_bank_2.setText("KRUNG THAI BANK")
        elif low2 == self.pay["LHB"]:
            self.lowest_bank_2.setText("LH BANK")
        elif low2 == self.pay["SCB"]:
            self.lowest_bank_2.setText("SIAM COMMERCIAL BANK")
        elif low2 == self.pay["TMB"]:
            self.lowest_bank_2.setText("TMB BANK")
        elif low2 == self.pay["UOB"]:
            self.lowest_bank_2.setText("KASIKORN BANK")
        self.lowest_pay_2.setText(str(low2))

        if low3 == self.pay["BKB"]:
            self.lowest_bank_3.setText("BANGKOK BANK")
        elif low3 == self.pay["BOA"]:
            self.lowest_bank_3.setText("BANG OF AYUDHYA")
        elif low3 == self.pay["CIMB"]:
            self.lowest_bank_3.setText("CIMB BANK")
        elif low3 == self.pay["GSB"]:
            self.lowest_bank_3.setText("GOVERNMENT SAVING BANK")
        elif low3 == self.pay["KBANK"]:
            self.lowest_bank_3.setText("KASIKORN BANK")
        elif low3 == self.pay["KTB"]:
            self.lowest_bank_3.setText("KRUNG THAI BANK")
        elif low3 == self.pay["LHB"]:
            self.lowest_bank_3.setText("LH BANK")
        elif low3 == self.pay["SCB"]:
            self.lowest_bank_3.setText("SIAM COMMERCIAL BANK")
        elif low3 == self.pay["TMB"]:
            self.lowest_bank_3.setText("TMB BANK")
        elif low3 == self.pay["UOB"]:
            self.lowest_bank_3.setText("KASIKORN BANK")
        self.lowest_pay_3.setText(str(low3))


        
    def retranslateUi(self, HOUSELOAN):
        _translate = QtCore.QCoreApplication.translate
        HOUSELOAN.setWindowTitle(_translate("HOUSELOAN", "MainWindow"))
        self.next_btn.setText(_translate("HOUSELOAN", "Next"))
        self.enter_name_label.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#826958;\">please enter your name</span></p></body></html>"))
        self.titel_label.setText(_translate("HOUSELOAN", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#cb773b;\">&quot;HOUSE LOAN&quot;</span></p></body></html>"))
        self.houseprice_label.setText(_translate("HOUSELOAN", "Price of House(THB)"))
        self.result_btn.setText(_translate("HOUSELOAN", "See Result"))
        self.info_label.setText(_translate("HOUSELOAN", "INFORMATION"))
        self.workBox.setTitle(_translate("HOUSELOAN", "Work Type"))
        self.work_ren_rad.setText(_translate("HOUSELOAN", "rentier"))
        self.work_gen_rad.setText(_translate("HOUSELOAN", "general"))
        self.insuBox.setTitle(_translate("HOUSELOAN", "Do you want to get an insurance?"))
        self.insu_no_rad.setText(_translate("HOUSELOAN", "no"))
        self.insu_yes_rad.setText(_translate("HOUSELOAN", "yes"))
        self.calculate_btn.setText(_translate("HOUSELOAN", "Calculate"))
        self.time_comboBox.setItemText(0, _translate("HOUSELOAN", "10"))
        self.time_comboBox.setItemText(1, _translate("HOUSELOAN", "15"))
        self.time_comboBox.setItemText(2, _translate("HOUSELOAN", "20"))
        self.time_comboBox.setItemText(3, _translate("HOUSELOAN", "25"))
        self.time_comboBox.setItemText(4, _translate("HOUSELOAN", "30"))
        self.label_30.setText(_translate("HOUSELOAN", "Time(Year)"))
        self.overall_label.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" font-weight:600; color:#e5be2e;\">Overall</span></p></body></html>"))
        self.BKB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Bangkok Bank: </span></p></body></html>"))
        self.golastpg_btn.setText(_translate("HOUSELOAN", "Next"))
        self.BOA.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Bank of Ayudhya:</span></p></body></html>"))
        self.CIMB.setText(_translate("HOUSELOAN", "<html><head/><body><p>CIMB THAI:</p></body></html>"))
        self.GSB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Government Saving Bank:</span></p></body></html>"))
        self.KBANK.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Kasikornbank:</span></p></body></html>"))
        self.KTB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Krung Thai Bank:</span></p></body></html>"))
        self.LHB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">LH Bank:</span></p></body></html>"))
        self.SCB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">Siam Commercial Bank:</span></p></body></html>"))
        self.TMB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">TMB Bank:</span></p></body></html>"))
        self.UOB.setText(_translate("HOUSELOAN", "<html><head/><body><p><span style=\" color:#cb773b;\">United Overseas Bank:</span></p></body></html>"))
        self.label_2.setText(_translate("HOUSELOAN", "Best Choice for "))
        self.label_26.setText(_translate("HOUSELOAN", "THB per month"))
        self.label_28.setText(_translate("HOUSELOAN", "Lowest Pay"))
        self.label_29.setText(_translate("HOUSELOAN", "(average pay per month)"))
        self.home_btn.setText(_translate("HOUSELOAN", "Back to Home"))
        self.exit_btn.setText(_translate("HOUSELOAN", "EXIT"))
        self.label_47.setText(_translate("HOUSELOAN", "THB per month"))
        self.label_48.setText(_translate("HOUSELOAN", "THB per month"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HOUSELOAN = QtWidgets.QMainWindow()
    ui = Ui_HOUSELOAN()
    ui.setupUi(HOUSELOAN)
    HOUSELOAN.show()
    sys.exit(app.exec_())
